/**
 * Builds the Audivo app (`ui/`) into one self-contained HTML document and
 * writes it to `src/app-html.ts`, which the server serves as the app
 * resource (ADR-0036). Run as `npm run build:ui`; `build-ui.test.ts` fails
 * when the committed file is not what the sources build, so the HTML the
 * package ships is always the HTML its sources describe.
 *
 * Script and styles are inlined because the app declares no domains: there
 * is nowhere else for them to come from.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, transform } from 'esbuild';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
export const OUTPUT = 'src/app-html.ts';

export async function buildAppHtml(): Promise<string> {
  const bundle = await build({
    entryPoints: [path.join(ROOT, 'ui/main.ts')],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'none',
    charset: 'utf8',
    write: false,
    logLevel: 'silent',
  });
  const script = bundle.outputFiles[0]!.text.trim();
  const styles = (
    await transform(fs.readFileSync(path.join(ROOT, 'ui/style.css'), 'utf8'), {
      loader: 'css',
      minify: true,
    })
  ).code.trim();
  // Either sequence would end the inline element early and turn the rest of
  // the bundle into page markup.
  if (/<\/script/i.test(script)) throw new Error('the app bundle contains </script');
  if (/<\/style/i.test(styles)) throw new Error('the app styles contain </style');
  return (
    '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    `<title>Audivo</title><style>${styles}</style></head>` +
    `<body><main id="app"></main><script type="module">${script}</script></body></html>`
  );
}

export function moduleSource(html: string): string {
  return (
    '// Generated by scripts/build-ui.ts from ui/. Do not edit: run `npm run build:ui`.\n' +
    `export const APP_HTML = ${JSON.stringify(html)};\n`
  );
}

const invokedDirectly =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const html = await buildAppHtml();
  fs.writeFileSync(path.join(ROOT, OUTPUT), moduleSource(html));
  process.stderr.write(`${OUTPUT}: ${html.length} characters\n`);
}
